package com.tazouxme.idp.application.exception.code;

public enum IdentityProviderExceptionCode {
	
	ACCESS_NOT_FOUND			(404, "ACCESS_NOT_FOUND"),
	ACCESS_ALREADY_EXISTS		(409, "ACCESS_ALREADY_EXISTS"),
	ACTIVATION_NOT_FOUND		(404, "ACTIVATION_NOT_FOUND"),
	ACTIVATION_ALREADY_EXISTS	(409, "ACTIVATION_ALREADY_EXISTS"),
	APPLICATION_NOT_FOUND		(404, "APPLICATION_NOT_FOUND"),
	APPLICATION_ALREADY_EXISTS	(409, "APPLICATION_ALREADY_EXISTS"),
	CLAIM_NOT_FOUND				(404, "CLAIM_NOT_FOUND"),
	CLAIM_ALREADY_EXISTS		(409, "CLAIM_ALREADY_EXISTS"),
	FEDERATION_NOT_FOUND		(404, "FEDERATION_NOT_FOUND"),
	FEDERATION_ALREADY_EXISTS	(409, "FEDERATION_ALREADY_EXISTS"),
	ORGANIZATION_NOT_FOUND		(404, "ORGANIZATION_NOT_FOUND"),
	ORGANIZATION_ALREADY_EXISTS	(409, "ORGANIZATION_ALREADY_EXISTS"),
	ROLE_NOT_FOUND				(404, "ROLE_NOT_FOUND"),
	ROLE_ALREADY_EXISTS			(409, "ROLE_ALREADY_EXISTS"),
	SESSION_NOT_FOUND			(404, "SESSION_NOT_FOUND"),
	SESSION_ALREADY_EXISTS		(409, "SESSION_ALREADY_EXISTS"),
	STORE_NOT_FOUND				(404, "STORE_NOT_FOUND"),
	STORE_ALREADY_EXISTS		(409, "STORE_ALREADY_EXISTS"),
	USER_NOT_FOUND				(404, "USER_NOT_FOUND"),
	USER_ALREADY_EXISTS			(409, "USER_ALREADY_EXISTS"),
	;
	
	private int status;
	private String code;
	
	private IdentityProviderExceptionCode(int status, String code) {
		this.status = status;
		this.code = code;
	}
	
	public int getStatus() {
		return status;
	}
	
	public String getCode() {
		return code;
	}

}
